language: python

python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"

before_install:
  - sudo rm -rf /etc/apt/sources.list.d/*
  - wget -O- http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
  - echo deb http://packages.couchbase.com/snapshot/ubuntu oneiric oneiric/main | sudo tee /etc/apt/sources.list.d/couchbase.list
  - sudo apt-get update
  - sudo apt-cache search libcouchbase

install:
  - sudo apt-get -y install libcouchbase-dev libcouchbase2-core libcouchbase2-libevent libevent-dev
  - pip -q install gevent || echo "Couldn't find gevent"
  - pip -q install twisted
  - pip -q install testresources
  - export CFLAGS='-std=c89 -pedantic -Wextra -Werror -Wno-long-long -Wno-missing-field-initializers'
  - python setup.py build_ext --inplace
  - sudo $(which python) setup.py install

script:
  - ./.ci_script.sh

notifications:
  email:
    - mark.nunberg@couchbase.com
